const KITCHEN_TICKET_KEYWORDS = [
  "food",
  "хоол",
  "шөл",
  "soup",
  "салат",
  "salad",
  "амттан",
  "dessert",
  "дессерт",
  "десерт",
  "тараг",
  "yogurt",
  "бялуу",
  "cake",
  "чизкейк",
  "cheesecake",
  "тирамису",
  "tiramisu",
  "панакота",
  "panna cotta",
  "пирог",
  "pie",
  "пицца",
  "пизза",
  "pizza",
  "паста",
  "pasta",
  "калзони",
  "calzone",
  "лазан",
  "lasagn",
  "болонез",
  "bolognese",
  "карбонара",
  "carbonara",
  "сүүтэй цай",
  "suutei tsai",
  "milk tea",
  "зөгийн балтай сүү",
  "зөгийн бал",
  "honey milk",
  "халуун вино",
  "халуун дарс",
  "hot wine",
  "mulled wine",
  "глинтвейн",
  "аарц",
  "халуун шоколад",
  "hot chocolate",
  "какао",
  "хачир",
  "монгол",
  "европ",
  "ази",
  "сет",
  "set",
];

const BAR_TICKET_KEYWORDS = [
  "чацаргана",
  "sea buckthorn",
  "зайрмаг",
  "ice cream",
  "мороженое",
  "печень",
  "жигнэмэг",
  "cookie",
  "cookies",
  "biscuit",
  "вафли",
  "wafer",
  "чихэр",
  "candy",
  "packaged sweet",
  "packaged sweets",
];

/** Shared routing for printed POS tickets and the kitchen queue. */
export function isKitchenTicketItem(item: { category?: string; name?: string }) {
  const text = `${item.category ?? ""} ${item.name ?? ""}`.normalize("NFKC").toLocaleLowerCase("mn-MN");
  if (BAR_TICKET_KEYWORDS.some(keyword => text.includes(keyword))) return false;
  return KITCHEN_TICKET_KEYWORDS.some(keyword => text.includes(keyword)) || text.includes("гал тогоо") || text.includes("kitchen");
}
