'use client';
import type { OpsRole } from '@/lib/auth-types';
import { useCallback, useEffect, useRef, useState } from 'react';
import { fetchWithTimeout } from '@/lib/client/network';
import { ProductShell } from './ProductShell';
import styles from './Products.module.css';
type Product={sku:string;name:string;category:string;guestPrice:number;staffPrice:number;stock:number;tracked:boolean};
export function Products({role}:{role:OpsRole}) {
 const [products,setProducts]=useState<Product[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [name,setName]=useState(''),[category,setCategory]=useState(''),[guest,setGuest]=useState(''),[staff,setStaff]=useState(''),[sku,setSku]=useState(''),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[kind,setKind]=useState('opening');
 const pending=useRef<{fingerprint:string;id:string}|null>(null);
 const refresh=useCallback(async(signal?:AbortSignal)=>{const res=await fetchWithTimeout('/api/products',{cache:'no-store',signal});const body=await res.json();if(!res.ok)throw Error(body.error||'Барааг ачаалж чадсангүй.');setProducts(body.products);setLoaded(true);},[]);
 useEffect(()=>{const c=new AbortController();fetchWithTimeout('/api/products',{cache:'no-store',signal:c.signal}).then(async res=>{const body=await res.json();if(!res.ok)throw Error(body.error||'Барааг ачаалж чадсангүй.');return body.products as Product[];}).then(items=>{setProducts(items);setLoaded(true);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 async function save(payload:Record<string,unknown>) {
  const fingerprint=JSON.stringify(payload);if(pending.current?.fingerprint!==fingerprint)pending.current={fingerprint,id:crypto.randomUUID()};
  setBusy(true);setMessage('');setError('');
  try {const res=await fetchWithTimeout('/api/products',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,clientRequestId:pending.current.id})},30000);const body=await res.json();if(!res.ok)throw Error(body.error||'Хадгалж чадсангүй.');pending.current=null;setMessage(`${body.sku} · ${payload.action==='create'?'Бараа нэмэгдлээ. Үлдэгдэл 0; орлогыг тусад нь бүртгэнэ.':'Орлого хадгалагдлаа.'}`);if(payload.action==='create'){setName('');setSku(body.sku);}else{setQuantity('');setReason('');}await refresh();}catch(e){setError(e instanceof Error?e.message:'Алдаа гарлаа.');}finally{setBusy(false);}
 }
 const selected=products.find(p=>p.sku===sku);
 const filtered=products.filter(p=>`${p.name} ${p.sku} ${p.category}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <ProductShell role={role}><header className={styles.title}><h1>Бараа ба үлдэгдэл</h1><p>Products &amp; stock · шинэ бараа, эхний тооллого, барааны орлого</p></header>{message&&<p className={styles.feedback} role="status">{message}</p>}{error&&<p className={styles.feedback} role="alert">{error}</p>}
 <div className={styles.forms}><form className={styles.section} onSubmit={e=>{e.preventDefault();void save({action:'create',name,category,guestPrice:Number(guest),staffPrice:Number(staff||0)});}}><h2>Шинэ бараа нэмэх</h2><p className={styles.muted}>SKU код автоматаар үүснэ. Ижил нэртэй барааг дахин нэмэхгүй.</p><label>Барааны нэр<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><label>Ангилал<input required list="product-categories" maxLength={100} value={category} onChange={e=>setCategory(e.target.value)}/></label><datalist id="product-categories">{[...new Set(products.map(p=>p.category).filter(Boolean))].sort().map(c=><option key={c} value={c}/>)}</datalist><label>Амрагчдын үнэ · ₮<input type="number" required min="0" max="1000000000" step="0.01" value={guest} onChange={e=>setGuest(e.target.value)}/></label><label>Ажилчдын үнэ · ₮<input type="number" min="0" max="1000000000" step="0.01" value={staff} onChange={e=>setStaff(e.target.value)}/></label><button type="submit" disabled={busy||!loaded}>Бараа нэмэх</button></form>
 <form className={styles.section} onSubmit={e=>{e.preventDefault();void save({action:'receive',sku,quantity:Number(quantity),reason,kind});}}><h2>Үлдэгдэл / орлого нэмэх</h2><p className={styles.muted}>Касс нээхээс өмнө бүртгэж болно. Энэ нь зөвхөн барааны тоонд нэмэгдэнэ; санхүүгийн баримтыг receipts.dalaieej.mn-д бүртгэнэ.</p><label>Бараа<select required value={sku} onChange={e=>setSku(e.target.value)}><option value="">Бараа сонгох</option>{products.filter(p=>p.tracked).map(p=><option key={p.sku} value={p.sku}>{p.name} · {p.sku} · {p.stock}</option>)}</select></label>{selected&&<p>Одоогийн үлдэгдэл: {selected.stock}</p>}<label>Төрөл<select value={kind} onChange={e=>setKind(e.target.value)}><option value="opening">Эхний тооллого / Opening stock</option><option value="delivery">Шинэ орлого / Delivery</option></select></label><label>Нэмэх тоо<input type="number" required min="0.001" max="1000000" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label>Тайлбар / нийлүүлэгч / баримтын дугаар<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Эхний тооллого эсвэл нийлүүлэгчийн баримт"/></label><button type="submit" disabled={busy||!loaded}>Орлого бүртгэх</button></form></div>
 <section className={styles.section}><h2>Барааны жагсаалт · {products.length}</h2><label>Хайх<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Нэр, SKU, ангилал"/></label>{!loaded?<p>Ачаалж байна…</p>:<div className={styles.tableWrap}><table><thead><tr><th>Бараа / SKU</th><th>Ангилал</th><th>Үнэ · ₮</th><th>Үлдэгдэл</th></tr></thead><tbody>{filtered.map(p=><tr key={p.sku}><td>{p.name}<br/><span className={styles.muted}>{p.sku}</span></td><td>{p.category}</td><td>{p.guestPrice.toLocaleString('en-GB')}</td><td>{p.tracked?p.stock:'Тоолохгүй'}</td></tr>)}</tbody></table>{!filtered.length&&<p>Бараа олдсонгүй.</p>}</div>}</section></ProductShell>;
}
